### ISSUE TITLE
Exclude ServerTasks from bootstrap trigger

### ISSUE THREAD

**Issue by andham** [gratex/oomph-task-server#3]
According to answer in the oomph forum, the ServerTasks (eg WebsphereServerTask) should probably not be performed in the installer but only in the installed application. To ensure this the bootstrap trigger should be excluded. Please see
https://www.eclipse.org/forums/index.php?t=msg&th=1086494&goto=1764499&#msg_1764499
for info on using an annotation on EClasses for this.

**Comment by andham** [comment]
I was able to workaround this misconfiguration in the task by adding
`excludedTriggers="BOOTSTRAP"`
to the declaration in my setup file.
Still running into other issues though, but this got me past the initial problem with the task being executed at bootstrap (see #2).

**Comment by koval-jan** [comment]
The BOOTSTRAP triger is removed in latest release

**Comment by andham** [comment]
@koval-jan Shouldn't you remove this trigger from the ServerTask class as well?

**Comment by koval-jan** [comment]
You are probably referring to this interface: com.gratex.oomph.task.server/src/com/gratex/oomph/task/server/ServerTask.java 

I figured that the file was not used (after several refactors ...)

**Comment by andham** [comment]
@koval-jan Yes, you're right.
