### ISSUE TITLE
Possibility to set auto connection settings for WAS

### ISSUE THREAD

**Issue by andham** [gratex/oomph-task-server#8]
Currently the IPC, RMI, and SOAP ports are configured for a WAS instance. I'd like the possibility to have this setting to be "Automatically determine connection settings" (which is the default when you create a WAS server instance via the GUI).

**Comment by koval-jan** [comment]
Should be fixed in release 1.0.17
I've introduced new config attribute profileName from which the settings will be read

**Comment by andham** [comment]
Not sure that's what I'm looking for. I was thinking more of having auto as default which is how it seems to work when creating from the UI. Now it's not due to this code:
`wasServer.setIsAutoConnectionTypeEnabled(false);`

**Comment by andham** [comment]
I tested attribute profileName and it doesn't help. "Manually provide connection settings" is still enabled instead of "Automatically determine connection settings".
Please reopen!

**Comment by koval-jan** [comment]
I've released 1.0.18 which should inclide the fix

**Comment by andham** [comment]
:+1: thanks!
